name: "Lint PR title"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - 'main'
      - 'develop'
jobs:
  lint:
    if: ${{ github.head_ref != 'develop' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if file exists
      id: check_file
      run: |
        if [ -f "commitlint.config.j" ]; then
          echo "::set-output name=file_exists::true"
        else
          echo "::set-output name=file_exists::false"
        fi

    - name: Install dependencies
      run: npm install @commitlint/cli @commitlint/config-conventional

    - name: Validate PR title
      run: |
        PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
        echo "$PR_TITLE" | npx commitlint --config commitlint.config.js
